/* USER */
export const ADD_USER = 'ADD_USER';
export const CLEAR_USER = 'CLEAR_USER';

/* ACCOUNT */
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT'

/* PRODUCT */
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'

/* PRODUCT PROFILE */
export const ADD_PRODUCT_PROFILE = 'ADD_PRODUCT_PROFILE'
export const EDIT_PRODUCT_PROFILE = 'EDIT_PRODUCT_PROFILE'
export const DELETE_PRODUCT_PROFILE = 'DELETE_PRODUCT_PROFILE'
export const CLEAR_PRODUCT_PROFILE = 'CLEAR_PRODUCT_PROFILE'